### ISSUE TITLE
Config examples/instructions

### ISSUE THREAD

**Issue by faeldray** [jbredwards/Well-Mod#3]
Could you provide some examples or instructions on how to configure the mod? For example, I'd like to make it generate the fresh water from TFC instead of vanilla water. Thanks!

**Comment by Foreck1** [comment]
I'm sorry it took this long to get to you, until we get a proper wiki set up, you can refer to this on how to configure custom fluids and biome

`{Data:[{MinTicks:50,MaxTicks:60,Fluid:{FluidName:"lava",Amount:1000},Biomes:["forest","plains"]`,
the Fluid arg forms a FluidStack using the same system forge uses (FluidStack.loadFluidStackFromNBT), the optional Biomes arg is just the biome registry names, and the optional BiomeTags arg gets all the biomes registered to a forge BiomeDictionary.Type, the MinTicks and MaxTicks are the amount of ticks between fluid gathering.
